### PR TITLE
Fix resizing issues with elipsis

### PR DESCRIPTION
**Pull request by alex-deaconu**
setting scrollLeft does not achieve the correct results
when using for Template Editor name with a CSS elipsis

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Fix required for https://github.com/Rise-Vision/rise-vision-apps/pull/1122.

@stulees @fjvallarino please review. Thanks!

**Comment by stulees** [comment]
@alex-deaconu Watched your video(s) regarding this specific issue in Apps PR. Looks good, can you confirm that removing this code doesn't cause any unwanted side effects for Template Editor name when ellipsis is _not_ required, and when modifying the name?

**Comment by alex-deaconu** [comment]
@stulees I was not able to identify any issues with the name (initialization or editing) when not using ellipsis. To confirm, I'm not 100% sure what the library intends to do with that particular code, but if I remove the ellipsis from the CSS and re-enable the scrollLeft this is what happens: https://screencast.com/t/NQmNgsNqyB.

I think the library is designed to scroll the content and show the tail end of it. In our case however we use the ellipsis which inhibits that behaviour.

So it's probably best to disable it. If we want the behaviour back for other elements, we can re-enable and conditionally disable for this use case.

Thanks.

**Review by fjvallarino — APPROVED** [review]
@alex-deaconu looks good 👍

**Review by stulees — APPROVED** [review]
@alex-deaconu Okay thanks for clarifying, looks good then 👍

**Pull request merged**
